### ISSUE TITLE
Array passed to setItems doesn't produce generated keys so x-delete can't find them.

### ISSUE THREAD

**Issue by bensherlock** [KaneCohen/tokenfield#10]
Hi,

Thanks for all your hard work on this library. 

I am using version: 0.3.9 via npm install. 

I have found that the array passed via "setItems" in the constructor correctly renders the tokens. But on clicking delete (the x) it removes them in order of the array rather than the specific item clicked. Any new items added via user input here are deleted correctly. On exploring the JSON output in "removeToken" it appears that any item created via setItems doesn't have a key and so can't be found in the Tokenfield key array. 

For example setting both items and newItems to:
[{id: 0, name: "Bob"}, {id: 1, name: "Bill"}, {id: 2, name: "Ben"}]
Clicking remove on Bill results in Bob disappearing whilst Bill and Ben remain. 
Likewise, clicking Ben first still results in Bob disappearing whilst leaving Bill and Ben. 

Hope this is enough information.

Thanks,
Ben

**Comment by KaneCohen** [comment]
Thanks for the report. Will see what's up. Most likely on init input array is not updated with unique keys identifying each item.

**Comment by KaneCohen** [comment]
Pushed 0.3.11. Should fix this issue.

**Comment by bensherlock** [comment]
Hi, Thanks for this. 0.3.10 fixes this perfectly. 

Unfortunately, the change between 0.3.10 and 0.3.11 introduces some Type exceptions as detailed in new issue #11 .

Thanks again.
Ben
