### ISSUE TITLE
Type error from chaining this._keyInput(e).focus()

### ISSUE THREAD

**Issue by bensherlock** [KaneCohen/tokenfield#11]
Thanks for such a speedy update!

Unfortunately, the change between 0.3.10 and 0.3.11 introduces some Type exceptions on:
line 721: this._removeItem(target.key)._renderItems()._keyInput(e).focus();

And when just clicking in the input box:
line 728: this._keyInput(e).focus();

Looking at the diff, for v0.3.10 it was:
this.focus();
this._keyInput(e);

Looking at the function for _keyInput(e) it generally returns "this" but in some cases returns "false". I guess it's when it returns false that we get the Type error when chaining functions.

Hope this helps,
Thanks,
Ben

**Comment by KaneCohen** [comment]
Pushed 0.3.12. Reverted changes in the chained functions order.
