### ISSUE TITLE
Resetting a form

### ISSUE THREAD

**Issue by activestylus** [KaneCohen/tokenfield#14]
When I run `document.getElementById("myForm").reset()` it clears all the fields, except for the tokeninput. There should definitely be some sort of callback function which clears the field when this event is triggered.

**Comment by KaneCohen** [comment]
Thanks, I'll see what would be the best way to implement it since tokenfield can't listen to the "reset" event on the input field itself (fields don't receive any events on reset of the form).

**Comment by KaneCohen** [comment]
Added new option "form" to the configs. By default tokenfield will listen to immediate parent form `reset` event which would trigger internal reset to initial list of items.

If set to falsy it wouldn't listen to the reset.

**Comment by activestylus** [comment]
Awesome! Thanks for rolling this out so quick
