### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by activestylus** [KaneCohen/tokenfield#16]
From the latest build, this is what happens when I update my tokeninput.js from your dit folder

**Comment by KaneCohen** [comment]
How do you load the library? Could you give a code example?

I don't know what `tokeninput.js` is in relation to tokenfield.

**Comment by KaneCohen** [comment]
Just tested it on 2 separate projects - one with babel, one with raw node. Module loads. Please provide more details.

**Comment by KaneCohen** [comment]
I've updated Babel library which compiles library slightly differently than before. That might be the reason.
