### ISSUE TITLE
Add option to trigger tokenisation on space key or comma key

### ISSUE THREAD

**Issue by codeKonami** [KaneCohen/tokenfield#17]
Hi,

First of all, thanks for this brilliant lib.

I was wondering, would it be possible to add options to choose if we want to trigger the tokenisation on the space key or comma key ?

Thanks

**Comment by KaneCohen** [comment]
@codeKonami it is technically possible using current options, however it would probably be a good idea to add input-based tokenization.

Right now you can use following config which would add token if you hit spacebar or coma (it relies on standard keyboard layout, though):

```ajs
new Tokenfield({
  keys: {
    32:  'delimiter',
    188: 'delimiter'
  }
});
````
With these options tokenfield would consider keys with keycode 32 and 188 to be delimieter-keys which initiate tokenization. I'll update this issue when I'll introduce new option which would trigger tokenization on the input content of the field, though.

**Comment by KaneCohen** [comment]
Update library version to `0.5.0`.

Now it has options `delimiters` which accepts array where you can add strings which would behave as delimiters during tokenization. Example:

````js
new Tokenfield({
 keys: {
    32:  'delimiter',
  },
  delimiters: [',']
});
````

Example above covers two events: user typing `,` or hitting enter, however you could also write it like so with a space as a delimiter:

````js
new Tokenfield({
  delimiters: [',', ' ']
});
````

**Comment by codeKonami** [comment]
Great! Thanks a lot for this quick upgrade!!
