### ISSUE TITLE
Multiple selection of tokens for deletion

### ISSUE THREAD

**Issue by codeKonami** [KaneCohen/tokenfield#18]
Would you consider adding the possibility to select multiple tokens? 

![token](https://cloud.githubusercontent.com/assets/1849998/22055297/cdbe2380-dd5a-11e6-9f19-6314b9e7c233.gif)

**Comment by KaneCohen** [comment]
@codeKonami I'll consider it.

**Comment by KaneCohen** [comment]
@codeKonami feature is available in latest version `0.6.1`.

**Comment by codeKonami** [comment]
Works really great, thank you for that. Just few things that are missing.

- Select All doesn't work (Ctrl+A or CMD+A)
- If you'd like to select a range of tokens and delete them, I need to keep the "Option" (Alt on Windows) button pressed otherwise if I move the cursor on some previous tokens and press the "Option" (Alt on Windows) key the cursor comes back the end of the line.

Example: I'm moving the cursor in the middle to select a range of tokens and when I want to start the selection press the Option + Cap keys.

![token2](https://cloud.githubusercontent.com/assets/1849998/22117748/71df7778-de75-11e6-83b1-a9bdf73068b4.gif)

This time if I keep the "Option" key pressed and start moving the cursor, I can press on CAPS and start my selection.

![token3](https://cloud.githubusercontent.com/assets/1849998/22117785/8dfea9ec-de75-11e6-92c9-35aca34dd777.gif)

**Comment by KaneCohen** [comment]
@codeKonami traditionally, for multiple selection you'd use SHIFT and CTRL. Shift selects range of items and Ctrl would select multiple items one by one.

**Comment by codeKonami** [comment]
I'm on MacOS so I don't remember how it works on Windows. But here is how I think it should work on Mac.

- SHIFT + CMD + Left Key should select all the tokens from the position of the cursor to the beginning
- SHIFT + CMD + Right Key should select all the tokens from the position of the cursor to the end of the tokens
- SHIFT + OPTION + Left Key should select the current cursor position selected and the one before
- SHIFT + OPTION + Right Key should select the current cursor position selected and the one after

**Comment by KaneCohen** [comment]
@codeKonami added "Ctrl+A/Cmd+A" shortcut to select all items in `0.6.4`. Fixed couple of multiselect related issue.

Option/Alt key is not supported for the multiple selection functionality since it has certain system related bindings on it. Besides, Ctrl and Shift are standard for that - for example layers in Photoshop use such shortcuts.

As for the listed custom shortcuts - those are way too specific. I'll consider making shortcuts extensible at some point.
