### ISSUE TITLE
on deleting any token from the list, it always deletes the first one

### ISSUE THREAD

**Issue by nakulsolanki** [KaneCohen/tokenfield#19]
i populated the tokenfield using setItems.
it displays the list correctly, but whenever i try to delete any token from the list using a mouse, it always deletes the first item from the list. 
If i use the backspace key , it deletes all items that were populated using SetItems.

**Comment by KaneCohen** [comment]
@nakulsolanki what version of the library do you use?

**Comment by KaneCohen** [comment]
@nakulsolanki OK, latest version `0.6.6` should fix the issue.

**Comment by nakulsolanki** [comment]
Its fixed... Awesome...
