### ISSUE TITLE
Sanitizing input value before adding token

### ISSUE THREAD

**Issue by simsim0709** [KaneCohen/tokenfield#2]
Hello, 

Thank you for your great plugin. I am very satisfied with yours. 

I have one question regarding sanitizing input value. Is there any way to sanitize value? 

I want to remove all of special characters and html tag before adding token, but I don't see any API.

Any suggestion? 

Thank you very much

**Comment by KaneCohen** [comment]
Just to make sure - are you talking about sanitizing value of each before rendering it?

Some simple example or better description might help to explain what you want specifically.

**Comment by simsim0709** [comment]
Yes. I am talking about sanitizing value of each before rendering it. 

For example, when a user type "#!$^(show me the money#$%^$" and press enter, I want it to be "show-me-the-money" something like this. 

And one more thing actually.. I actually set option itemValue as '_id' not 'id', but it seems like not working properly.

It seems like Tokenfield always need 'id' property to work properly. If no id provided in items, keyboard control not work well.

Is that Yes? or am I missing something?

**Comment by KaneCohen** [comment]
OK, I got what you meant about sanitizing. I'll add a way to sanitize data.

Regarding `itemValue` property. This is a property which is taken from individual token object and which is assigned to the hidden `<input>` value. For example consider following small data sample:

````js
[
    {id: 1, name: 'red', foo: 'hello'},
    {id: 2, name:'orange', foo: 'world'}
]
````

Each object in an array represents each token available to tokenfield. When you set `itemValue` to `id` it will use `id` property from each object and assign it to the hidden <input>. For our datasable it would be 1 and 2 if `itemValue` is `id`. If `itemValue` is set to `foo`, then for each token input would have 'hello' and 'world'. So, make sure that each token in a dataset have property which is set in `itemValue`.

Not sure what's the issue with keyboard controls. Even if I set `itemValue` to a nonexistent property - keyboard actions still work as expected. I need more data on that issue.

**Comment by KaneCohen** [comment]
@simsim0709 
I've updated library to version 0.3.0 with couple of extra methods you can work with.

In order to sanitize data you can override a helper method `rederSetItemLabel` where you can do whatever you want with a given item, including sanitizing output.

Here's a small example: 

````js
var myTokenfield = new Tokenfield({
  el: document.querySelector('.text-input'),
  items: [
    {id: 1, name: 'red'},
    {id: 2, name:'orange'},
    {id: 3, name: 'yellow'}
  ],
  newItems: false
});

// Sanitize label content.
myTokenfield.renderSetItemLabel = function(item) {
  return item.name.replace(/[^a-z0-9]/gi, '');
}
````

**Comment by simsim0709** [comment]
Thank you for your help. 

`
const tf = new Tokenfield({
      el: tagInputRef,
      items: [
        {
            "_id" : "E27SsP7gACKNsDJWs",
            "name" : "tag",
            "createdAt" : ISODate("2016-06-28T10:47:52.795Z"),
            "count" : 8,
            "updatedAt" : ISODate("2016-06-28T10:47:52.796Z")
        },
        {
            "_id" : "a86d6QBANJGPhzaZw",
            "name" : "taglist",
            "createdAt" : ISODate("2016-06-28T07:18:52.076Z"),
            "count" : 2,
            "updatedAt" : ISODate("2016-06-28T07:18:52.076Z")
        },
        {
            "_id" : "5Rzq3bSFRxQWDE7Wf",
            "name" : "tagmore",
            "createdAt" : ISODate("2016-06-28T07:18:54.774Z"),
            "count" : 2,
            "updatedAt" : ISODate("2016-06-28T07:18:54.774Z")
        }
      ],
      itemValue: '_id',
    });
`

this is taken from my source. As you see above, there is no "id" property of my data. And I set ItemValue property to be "_id". 

as you see the gif file. I see this bug. Am I missing something??

![ezgif-2820317496](https://cloud.githubusercontent.com/assets/10040154/16414506/f4d01858-3d72-11e6-9f71-6c176655a986.gif)

**Comment by KaneCohen** [comment]
OK, I managed to reproduce the issue with given data. Looking into the root of the issue.

**Comment by KaneCohen** [comment]
@simsim0709 updated to version 0.3.2. Should cover your issue.

**Comment by simsim0709** [comment]
That's great. I just updated to version 0.3.2, and it works very well.

Thank you.
