### ISSUE TITLE
Delimiters on MacOs Safari doesn't work

### ISSUE THREAD

**Issue by codeKonami** [KaneCohen/tokenfield#21]
I've set some custom delimiters like this
```js
var tf = new Tokenfield({
      el: document.querySelector('.tags-input'),
      delimiters: [',', ' '],
      maxItems: 5
    });
```

It's working perfectly on Google Chrome but it doesn't work on Safari. The delimiters don't trigger the creation of a token

**Comment by KaneCohen** [comment]
Thanks for the report. I'll see what's up with that.

**Comment by KaneCohen** [comment]
@codeKonami what's your Safari and Mac OS version? Just tried on Sierra Safari 10.0. Works as expected.

**Comment by codeKonami** [comment]
that's strange I'm on Mac OS Sierra 10.12.2 with Safari 10.0.2

**Comment by KaneCohen** [comment]
Try last library version just in case (0.6.11)? I'll try updating safari to the latest version and see if I'll be able to reproduce the issue.

**Comment by codeKonami** [comment]
Same problem with the 0.6.11

Let me know if I can do something to help you out.

**Comment by KaneCohen** [comment]
@codeKonami btw. Did you set option `addItemsOnPaste` to true?

Example
```js
var tf = new Tokenfield({
      el: document.querySelector('.tags-input'),
      delimiters: [',', ' '],
      maxItems: 5,
      addItemsOnPaste: true
    })
```

**Comment by codeKonami** [comment]
No I did not. I've tried with addItemsOnPaste: true, it is still not working but it's working by pasting (look the gif enclosed)

![delimiter-bug](https://cloud.githubusercontent.com/assets/1849998/24836611/8376770e-1d20-11e7-9a10-bd4166ddf426.gif)

**Comment by KaneCohen** [comment]
Got you. I'll investigate it further.

**Comment by KaneCohen** [comment]
@codeKonami updated library. `v0.6.12` fixes this issue.
