### ISSUE TITLE
removedItem doesn't return item removed

### ISSUE THREAD

**Issue by aabanaag** [KaneCohen/tokenfield#22]
removedItem event doesn't return item removed like the documentation specifies.

**Comment by KaneCohen** [comment]
I guess you mean `removedToken` event? It does appear that it's not returning removed item.

**Comment by KaneCohen** [comment]
Should be fixed in latest version (`0.7.5)`.

**Comment by aabanaag** [comment]
Oh. Just a question how append data to tokenField? Tried setItems but not
working

**Comment by KaneCohen** [comment]
`setItems` should be working if you provide correct data. Could you give an example of the data you add in `setItems()`?

**Comment by aabanaag** [comment]
my code is like this
```
let tf = new TokenField({ el: ... });
tf.setItems(data);
```

**Comment by KaneCohen** [comment]
What's in `data` variable?

**Comment by aabanaag** [comment]
```
[{name: 'test', role: 'text', _id: ''test'}, ...]
```

**Comment by KaneCohen** [comment]
Data seems to be correct. Tried on my local instance - works fine. Do you have any errors in console? Do you overwrite any of the item rendering functions?

**Comment by aabanaag** [comment]
![image](https://cloud.githubusercontent.com/assets/2245822/26765645/c712e1aa-49b2-11e7-9bd7-0c1534a11caa.png)
I only get this

**Comment by aabanaag** [comment]
should it be id not _id?

**Comment by aabanaag** [comment]
its working now. A dumb mistake on my part tho. Thank you for being so helpful. cheers. 👍

**Comment by KaneCohen** [comment]
Awesome. Have a good day.
