### ISSUE TITLE
Delete item click event not firing on mobile

### ISSUE THREAD

**Issue by alecrubin** [KaneCohen/tokenfield#23]
The delete item on click event works on desktop, but not touch-enabled devices. Not really sure what the issue is.

**Comment by KaneCohen** [comment]
Thanks, I'll take a look. What device/browser are you using?

**Comment by KaneCohen** [comment]
Should be fixed. I've changed element that was wrapping item remove button to anchor `<a>` in order to improve event chatching by the browser. Should be more reliable now.

Make sure to upgrade to v0.7.6.
