### ISSUE TITLE
Support jQuery ajax options

### ISSUE THREAD

**Issue by davidesigner** [KaneCohen/tokenfield#24]
Hi there,

thanks for your module!

I am looking to replace the [bootstrap-tokenfield](https://github.com/sliptree/bootstrap-tokenfield) module by yours but I need to add headers to my ajax request.

Here is my jQuery ajax function:
```
$.ajax({
	url: 'api.domain.com/tags',
	data: {query: request.term},
	beforeSend: (xhr) => {
		xhr.setRequestHeader('Authorization', 'Bearer ' + adminApiToken);
	},
	success: (data) => {
		const transformed = $.map(data.tags, (el) => {
			return {
				id: el.name,
				name: el.name
			};
		});
		response(transformed);
	},
	error: () => {
		response([]);
	}
});
```
So, I need to use the `beforeSend` and maybe the `success` option to parse the returned json object. Have you a solution to do that?

Thanks!

**Comment by KaneCohen** [comment]
I'll see how this could be accomplished - maybe would add an option to inject own XHR code.

**Comment by KaneCohen** [comment]
@davidesigner took a bit of time, but latest version of tokenfield (`0.8.1`) supports XHR headers done via:
```js
remote: {
    headers: {
        Authorization: 'Bearer ' + adminApiToken
    } 
}
```

As for a data processing on success - you can use method `Tokenfield.remapData`.
What you do is overwrite that method on your tokenfield instance:

```js
myTokenfield.remapData = function(response) {
    // This method must return processed according to standard Tokenfield format data.
    return response.items;
}
```
