### ISSUE TITLE
Possibility to post value as one string?

### ISSUE THREAD

**Issue by donaldtbd** [KaneCohen/tokenfield#27]
Hello,

Im trying to replace an existing tokenfield with your implementation. 
The problem is my backend is supporting only one string value per tokenfield because previosuly it just stored coma seperated values like "red, green, blue".
Can your tokenfield be configured to post its content as one value (may be JSON) and later use that string to repopulate the tokenfield?

For example tokenfield setItems() currently accepts following format for input:
[{id: 1, name: 'red'}, {id: 2, name: 'orange'}, {id: 0, name: 'new1'},{id: 0, name: 'new2'}]
This is something i could store in my backend database without any changes.

Is it possible to configure the tokenfilt to also output the same format as it expects for input?

**Comment by KaneCohen** [comment]
Unfortunately, right now there's no way to configure tokenfield to behave the way you want to.

You could add an event listener which would fill some input field you have with required data, something like that:

```js
var input = document.querySelector()
tokenfield.on('change', function() {
    tokenfield._html.input.value = tokenfield.getItems().reduce(function(val, item) {
        return val + ', ' + item.name;
    }, '');
});
```

I'll consider adding an option to handle input the way you describe as a single string.

**Comment by donaldtbd** [comment]
Thanks, Ill implement an adapter for now and keep my eyes open for the feature :) In general I think its very useful and also a good practice for a field to output the same format and structure as it expects as input.

**Comment by KaneCohen** [comment]
@donaldtbd Tokenfield v0.9.0 now supports an option where you can specify a single input field where tokens will be stored alongside normal array-type method.

To be specific, there are three options you need to specify (not necessary all of them):

```js
singleInput: false,
singleInputValue: 'id',
singleInputDelimiter: ', ',
```

First option, `singleInput` tells Tokenfield whether it should store data in an input. That field accepts either boolean (if set to true - then it will consider `el` option as an input) or HTML element or query selector string.

Second option `singleInputValue` specifies which property from an item object will be used when inserted into input. By default it's `id`, but you can set `name` or any other. In your example it seems like should be `name`.

Third option `singleInputDelimiter` specifies what character(s) would be used to separate each item in the input.

**Comment by mguidetti** [comment]
Thanks for adding this feature! I believe its documentation is missing from the main readme though, I had to come to this issue to find it.
