### ISSUE TITLE
"maxSuggests" in documentation should be "maxSuggest" + scrolling question

### ISSUE THREAD

**Issue by Delphiki7** [KaneCohen/tokenfield#28]
Hi,

First of all i have to mention its a great library and suits my needs almost exactly. Great job! :)

The only problematic part for me is that i have a really long list of items and i want the user to be able to see and choose from them all. First i tried changing the "maxSuggest" property and found a little typo there. It is refered to as "maxSuggests" in doc, but when trying out it didn't work. So i digged a bit into the library and it seems that the correct property is "maxSuggest".

But setting maxSuggest higher didn't really give me the result i wanted. That just opened a really long dropdown and made a scrollbar on the page. My question is that is it possible to open a dropdown with 10 items but also have a scrollbar within that dropdown so i can view more items?

Here as an example of my list with higher "maxSuggest":
https://jsfiddle.net/oL6cL8bz/1/

**Comment by KaneCohen** [comment]
I'll look into adding an option to allow scrollable suggestions. However in the meantime you could just change CSS where you'd set specific `max-height` to a suggestions list and set it to `overflow: auto`.

**Comment by KaneCohen** [comment]
@Delphiki7 Tokenfield v0.9.0 now supports an option where you can specify how many maximum numbers should be visible within the suggested list.

That options is a `maxSuggestWindow` by default is set to 10 and it works alongside option `maxSuggest`. When set to specific amount that is lower than `maxSuggest` it would turn suggestion box into a scrollable box.

You can check your updated example here: https://jsfiddle.net/1erz7j0e/1/
