### ISSUE TITLE
Tokenfield not supported by internet explorer 11?

### ISSUE THREAD

**Issue by Delphiki7** [KaneCohen/tokenfield#29]
Hello,

When using ie11 tokens are not shown and dropdown does not open on example page http://kanecohen.github.io/tokenfield/

Would it be possible to support ie11 aswell? This is the best tokenfield plugin available, but ie11 is still used a lot so not supporting it would be a pretty serious limitation.

**Comment by KaneCohen** [comment]
Yeah, currently there are some JS code which IE11 doesn't like. I'll look into refactoring that to support IE11 in the next couple of days.

**Comment by joekalda** [comment]
Also having the same problem. Any updates on the fix? :)

**Comment by KaneCohen** [comment]
Will make a patch some time this week.

**Comment by KaneCohen** [comment]
IE11 support added in version `0.9.1`.
