### ISSUE TITLE
After choosing an option from the end of dropdown it is reset back to beginning

### ISSUE THREAD

**Issue by Delphiki7** [KaneCohen/tokenfield#30]
Hi,

Here is an example of what i mean: https://jsfiddle.net/1erz7j0e/1/

To reproduce:
1) Click on input field
2) Scroll to the end
3) Select option "25"

Actual result:
Dropdown is reset back to beginning of dropdown with options 1,2,3,4,5 visible.

Expected result:
Dropdown remains where it was with options 20,21,22,23,24 visible.

Is there an option to achieve the desired result? Or if not maybe you can suggest workaround that i could implement?

**Comment by KaneCohen** [comment]
Hi, thanks for the report. Unfortunately right now there's no workaround - I'll update the code which should prevent scroll reset.

**Comment by KaneCohen** [comment]
I've updated library to version 0.9.2 where this issue should be fixed.

**Comment by Delphiki7** [comment]
Wow, that was fast, thanks! :)
