### ISSUE TITLE
Exception on filtering suggestions

### ISSUE THREAD

**Issue by jgasiorowski** [KaneCohen/tokenfield#31]
https://github.com/KaneCohen/tokenfield/blob/3ec24c43691685308e5db2482e96136077d9e87b/lib/tokenfield.js#L1358
In referenced code I get `Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.`.
It happens when after typing a letter I am about to filter out multiple items - `for` loop is removing items based on old indexes of collection which is changing in each iteration - in the end it calls `.removeChild()` function with `undefined` parameter

**Comment by KaneCohen** [comment]
Fixed in `v0.9.3`.

When running removeChild it would remove first overflow child, then next one, however overflow items would keep decreasing and at some point index which accesses them would overflow.

**Comment by KaneCohen** [comment]
Actually, get version `v0.9.4` it has additional bugfix for a visual issue.

**Comment by jgasiorowski** [comment]
Thanks I will check it tomorrow. BTW is there any posibility that you could provide not minified version of your library? I just want to use it same way as `.min.js` but it is easier for debugging. Current not minified versions force me to use module bundler

**Comment by KaneCohen** [comment]
Don't see why not. You can already find the non-minified version of the library in `/lib` directory, however it's written in a more modern ECMAScript, which might not work on older browsers.

**Comment by KaneCohen** [comment]
`tokenfield.web.js` has been added in `v0.9.5` or available in `dist/` on master branch.

**Comment by jgasiorowski** [comment]
Thank you once again. Fastest updates I've ever seen ;) I confirm that issue is fixed and `.web.js` version works like a charm!
