### ISSUE TITLE
IE11 "Unable to get property 'readyState' of undefined or null reference"

### ISSUE THREAD

**Issue by eddturtle** [KaneCohen/tokenfield#32]
Hi, we're having some issues only on IE (tested with version 11). We're using it to make ajax calls to fetch the data.

Think it's related to this section of the code:
https://github.com/KaneCohen/tokenfield/blob/master/dist/tokenfield.js#L487

The error looks like this: https://www.dropbox.com/s/e885m8qdw5knnr5/send-email-from-doc-script-issue.jpg?dl=0

Do you have any ideas of how to help us, or where we could look to fix it for a pr?

**Comment by KaneCohen** [comment]
Not really any easy solution - you could replace "fetchData" method of the class with your custom version.

I'll check IE documentation to see what is used to handle AJAX requests.

**Comment by eddturtle** [comment]
Should something like this work in IE11 (code below)? I'm trying to work out where the issue lies and happy to make a pull request if this is suppose to work and isn't but it might be something we're doing - or maybe remote data isn't supported in IE11?
 
```js
new Tokenfield({
    el: document.getElementById('example'),
    remote: {
        type: 'GET',
        url: "r/search",
        queryParam: 'query',
        delay: 300
    }
});
```
Do you think an extra 'is not null' check would be worth doing on xhr before reading the readyState - might fix it?

**Comment by KaneCohen** [comment]
@eddturtle I've pushed `v0.9.6` which should fix this issue.

Not quite clear on why it happens (I guess some IE quirk), but first callback for ajax request is always ends up having xhr set to null. I've added a null check in there, so error won't be thrown.
