### ISSUE TITLE
Space can't be use

### ISSUE THREAD

**Issue by anthonyBertrant** [KaneCohen/tokenfield#33]
Hi, first: Great work !! Your module is saving me a looooot of time !!! But, maybe it's only me, when I type a token, it's reconize only when I press tab or enter key, not when I press space. I think, if it's not a probleme, it will be interesting to implement this new possibility.

Sorry for my bad english, I'm french (I surrender..)

**Comment by KaneCohen** [comment]
Hi, Anthony. Glad this library is of use.

By default `space` is not used for tokenization - however it is easy to make it work. All you need to do is set space key code to be considered as a delimiter. Here's an en ample: 

```js
new Tokenfield({
  keys: {
    9: 'delimiter',
  }
});
```

**Comment by KaneCohen** [comment]
Updated example above - "space" key should be `32`.

**Comment by anthonyBertrant** [comment]
Okay ! I found an another solution too. In your docs you talks about a delimiter param. I just add " " and it’s works ! Thanks for your help, and good job for your module
