### ISSUE TITLE
Can't change matching parameters

### ISSUE THREAD

**Issue by Prestaworks** [KaneCohen/tokenfield#34]
Would be great to have a way to change if the matching is done on a few different settings, like say beginning and end of string and not just "inside" string as it is now.

**Comment by KaneCohen** [comment]
@Prestaworks pushed `v0.9.8`. It contains following matching options:


| Name | Type | Default | Description |
| ---- | ---- | ------- | ----------- |
matchRegex | string | `'{value}'` | Regex string that would be used for matching - when regex is compiled {value} would be replaced with escaped user input.
matchFlags | string | `'i'` | Regex flags used in matching. Default is i - case insensitive matching.
matchStart | bool | `false` | Option to do matching only from the beginning of the string - it compiles match regex to basicall this format: /^{value}/i.|
| matchEnd | bool | `false` | Option to do matching only from the end of the string - it compiles match regex to basicall this format: `/{value}$/i`. |

If you just need to do matching at the beginning or at the end, just use `matchStart: true` or `matchEnd: true`.
For more complex matching `matchRegex: '{value}'` could be used
