### ISSUE TITLE
Use Tokenfield with textarea

### ISSUE THREAD

**Issue by rifton007** [KaneCohen/tokenfield#35]
Hi and thank you for your repository.

I would like to use Tokenfild with textarea, is it possible ?
I defined `inputType: 'textarea'` in the options, but it didn't work.
Thank you for your help.

**Comment by KaneCohen** [comment]
Unfortunately not. `inputType` - is the type that is being set for `<input>` element where you type when tokenfield is focused. It accepts values such as `text`, `email`, `url` and so on.

Could you give an example of where `textarea` could be used as an input? I could try looking into adding it if it's something common.

**Comment by rifton007** [comment]
Hi @KaneCohen,
Yes, I want using a textarea to put many email addresses.

**Comment by KaneCohen** [comment]
Hi,
Not quite sure why textarea is necessary there. Tokenfield would grow in height automatically if you add multiple items, so if it's the matter of size, it shouldn't really matter.

**Comment by rifton007** [comment]
I know, technically it's working.
But in some case, this isn't esthetics to use a simple input text.
![image](https://user-images.githubusercontent.com/2601347/42574350-89c73c76-851e-11e8-8f74-02bc4c2398b2.png)

**Comment by KaneCohen** [comment]
I see what you mean.
I would recommend changing `.tokenfield` element style by adding `min-height`. Don't think `textarea` would have been helpful here.

**Comment by rifton007** [comment]
I have tried with a input text and textarea, but it doesn't work
css
```
.tokenfield {
    min-height : 100%;
}
```

**Comment by KaneCohen** [comment]
`min-height: 100%` wouldn't work here unless you use flexbox i think. You might want to add specific height: something like `300px`.

Here's a really rough example of how flexbox could help: <http://jsfiddle.net/0auoLhpb/>

**Comment by rifton007** [comment]
It's okay, thank you @KaneCohen
