### ISSUE TITLE
re-order tags?

### ISSUE THREAD

**Issue by heldchen** [KaneCohen/tokenfield#36]
the module looks great! any plans to add drag-n-drop reordering?

**Comment by KaneCohen** [comment]
Hi. It's in the "nice to have" list of features, however I'm not sure when and how it would be added.

I would prefer not to implement sorting/dragging within tokenfield in order to keep size of the library as small as possible, so it would have to somehow rely on external library.

For now I can only recommend using something like <https://github.com/RubaXa/Sortable> and implementing sorting yourself.

**Comment by heldchen** [comment]
thanks for the superfast reply, appreciated! 

while an external library would indeed visually order the tags, upon form submission the order is actually split between `items[]` and `items_new[]`. is there an option to use `name="items[]"` for both existing and new keys? the existing `singleInput` option does not seem to do that...

**Comment by KaneCohen** [comment]
In the options set `newItemName` to `items` if you want existing and new items to be available within the same input in the backend.

**Comment by heldchen** [comment]
ah perfect, thanks again!

**Comment by KaneCohen** [comment]
@heldchen I've pushed a small update which should make life a bit easier for dealing with tokens order.

First: `items` and `items_new` now would be keeping the same order as it appears in the tokenfield.

For example: if you have tokes like this where numbers are existing tokens and string is a new token:

```1, 2, "Foo", 3```

They would be send to the backend in the following format:
```js
items[0] = 1
items[1] = 2
items[3] = 3
items_new[2] = "Foo"
```

This should allow you to add specific position to a given token.

Second: as a helper function for and external sortable library - you can call method `tokenfield.sortItems()` which would take list of current items in the tokenfield and internally arrange it in the same way as it appears in the tokenfield.

For example, in a library Sortable you can set following event
```js
onSort: function() {
  tokenfield.sortItems();
}
```

**Comment by heldchen** [comment]
that is really helpful, thanks!
