### ISSUE TITLE
Empty a token field

### ISSUE THREAD

**Issue by ErnestBrandi** [KaneCohen/tokenfield#38]
Hi,

I'd just appreciate a public function that allows me to empty my keywords field.

Thanks

**Comment by ErnestBrandi** [comment]
Was looking for that. Do you have a more precise doc somewhere ?

**Comment by KaneCohen** [comment]
No, I will update docs for extra things that accumulated.

**Comment by ErnestBrandi** [comment]
Thanks :)

**Comment by ErnestBrandi** [comment]
Same, what is the best way to add a token through code. Tried `addItems("foo")` but it adds an empty token (with only the cross to close it).

**Comment by ErnestBrandi** [comment]
Seems to be an issue with `renderSetItemLabel()` and the fact that items added that way (and stored in the `setItems` array) do not have a `name ` attribute.

**Comment by KaneCohen** [comment]
addItems("foo") - expect an object in the format of `{id: 1, name: 'Red'}` as described in the docs. It can't be a string.

Which is related to the `renderSetItemLabel()`.

**Comment by KaneCohen** [comment]
If you just want to add new token without an ID, you could use non-public method `_newItem('foo')`,.

**Comment by ErnestBrandi** [comment]
Uh, the doc was clear about format indeed... Tried `_newItem('foo')` before, but it doesn't work. Plus, with `addItems({"id": id, "name": "foo"})` the value of hidden input `.item-input` is equal to the id and not the name. This is confusing as this not the case for a token entered through input (who has no id). Then it is hard to know if we work with an id or with new data.

**Comment by ErnestBrandi** [comment]
My bad I just noticed new elements was stored in a separate array.

**Comment by KaneCohen** [comment]
In `v1.0.1` you can do `addItems({isNew: true, name: 'Hello'})` which would add new token instead of using internal `_newItem()`.
