### ISSUE TITLE
Change possible items for a field

### ISSUE THREAD

**Issue by rickmacgillis** [KaneCohen/tokenfield#43]
I'm trying to change the suggestable items after they've been set. For example, we have a categories list that sets certain skills exclusive to that category. When someone chooses to a different category after we've already set the skills list on the token field, we need to change the suggestable items to match the new category.

I can check if the field is already set to an instance of a Tokenfield object, but when it exists, what do I do to change the items?

Here's a video demonstration of what I'm trying to achieve.
https://www.useloom.com/share/e5c8a6f8395f4033a51d7a544dcae084

EDIT:
As a temporary workaround, I made a container in which to place the Tokenfield. I them made a template of the input textbox, and set its CSS to `display:none`. That made it so I could use jQuery to delete and remove all Tokenfield HTML code, essentially resetting the field. However, I don't know if the hooks are now messed up or not. Perhaps @KaneCohen knows of a cleaner solution which he could implement in a nice method for the Tokenfield object?

**Comment by KaneCohen** [comment]
Hi. If I understand correctly - when you create a Tokenfield instance you set an option `items`. Which you want to change later based on some event in the app?

**Comment by rickmacgillis** [comment]
@KaneCohen Correct.

**Comment by KaneCohen** [comment]
Currently you could try doing following:

```js
let inst = new Tokenfield(...);

// In the event:
inst._options.items = [{...new item...}, {...new item...}];
```

I'll have to add some method to add that in a more reasonable way later.

**Comment by rickmacgillis** [comment]
Thank you. When I work with it again I'll try it out. It'll probably be a couple weeks before I have a chance, though.

**Comment by KaneCohen** [comment]
I'll add some method by that time.

**Comment by rickmacgillis** [comment]
@KaneCohen - Even better! Thank you.

**Comment by KaneCohen** [comment]
In `v.1.3.0` you can now run `setSuggestedItems(items)` to inject new list of possible items for suggestion.
