### ISSUE TITLE
Question about newItems feature

### ISSUE THREAD

**Issue by RDiazR2** [KaneCohen/tokenfield#47]
Hello @KaneCohen 

Thanks a lot for your tokenfield component. It's very valuable.

I have a question regarding newItems function. Can I check the newItem value before being added to the component? I would like to check with a regular expression to accept or reject the new values. Do you have any suggestion how can I implement this?

Thanks a lot

**Comment by KaneCohen** [comment]
@RDiazR2 hi. Currently there's no built-in function to validate new items. I'll see if I can add it within next couple of days.

**Comment by KaneCohen** [comment]
@RDiazR2 added optional parameter: `validateNewItem` which can be specified along other options (check readme). If returns `true` - new item is added. If `falsy` return - item not added.

**Comment by RDiazR2** [comment]
Thank a lot, @KaneCohen !!!
