### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by felix9607** [KaneCohen/tokenfield#49]
I get this weird behavior, mainly focused for Vue Projects. I tried different browsers etc, nothing helped.
I just use the very basics funtionallities.

<img width="285" alt="image" src="https://user-images.githubusercontent.com/31954552/94122201-90e63200-fe52-11ea-9ffd-4aea30ba4fd1.png">

https://codesandbox.io/s/ui5-webcomponents-forked-rww64?fontsize=14&hidenavigation=1&theme=dark

**Comment by KaneCohen** [comment]
It appears that you didn't load the styling.
Here's forked sandbox code with styles added: https://codesandbox.io/s/ui5-webcomponents-forked-2byrs?file=/src/index.js

Keep in mind - by default it's expected to run on top of Bootstrap. If you are implementing it without bootstrap - you can check 
scss files here and use them in your project: https://github.com/KaneCohen/tokenfield/tree/master/lib/scss

**Comment by felix9607** [comment]
Thanks, that was my fault!
