### ISSUE TITLE
Feature request: Grouping of tags

### ISSUE THREAD

**Issue by cal-zone** [KaneCohen/tokenfield#51]
I would love the ability to create groups of tags (like optgroups in a select) or hierarchical tags.

Such functionality should enable segregating all available tags according to the group they're assigned to and styling each group differently (use different colors). Creating group headers and dividers would be ideal.

Additionally, when the autocomplete dropdown appears, regardless, of this grouping feature, the available options should ideally be styled as inline-block tags by default (instead of rows of plaintext).

**Comment by KaneCohen** [comment]
Regarding optgroups - highly unlikely that it would be added.

Not entirely sure what you mean by using inline-block for suggested options - if necessary you could always apply your custom styles for desired result.

**Comment by cal-zone** [comment]
I mean to display the available options in a 2-D layout… grid, table. What I did was make my li element display:inline-block because otherwise, when you have a lot of tags, it is too much to scroll through… at the same time, a user who does not know which tags are available, will not know what to type to search and could waste a lot of time trying different words hoping to find the exact tag they want. 

My use case is one where displaying all or as many of the allowed results as possible to the user, all at once makes it fast and easy to scan and either type the letters of the tag they want or tap/click on the tag they want when they see it. Having the ability to type (especially if optgroups were an available feature) would also allow the user to filter the field of possible down to certain type of tags or tags that match a certain criteria. In this way, a system with 200 tags is usable by someone who doesn't know which tags are in use and allowed.

I believe the use case I am describing is actually extremely common. Particularly for applications where data integrity is important (i.e. you need strict tag definitions and no near-duplicates).

**Comment by KaneCohen** [comment]
OK, I understand, however by default display of suggested items will remain as it is being rather more traditional.

Any other display format would simply require custom CSS which is why Tokenfield has as few styles as possible to not obstruct customization of the look.
