### ISSUE TITLE
Potential improvements and trigger input field

### ISSUE THREAD

**Issue by PierreChls** [KaneCohen/tokenfield#6]
To begin, congralutations for your work, your lib is very cool and very easy to use. 👍🏻

### Potential improvements

It would be great to add keys options on your Tokenfield init. It would allow to customise our key event and token delimiter. We could delimite token with space, slash... and not only the enter key.

### Trigger input field

I use a virtual keyboard for my app and I would trigger an "*enter*" event when a button is triggered. 

- I initialized my input like this 

```javascript
<input id="e-mail-input" placeholder="Add your e-mails friend" />
```

- And I initialized my Tokenfield like this : 

```javascript
const tokenfield = new Tokenfield({
    el: document.querySelector('#e-mail-input'),
    maxItems: 4
})
```

But when I add a keypress listener, there are any events...

```javascript
$('#e-mail-input').keypress(function(e) {
    if (e.which == 13) {
        console.log('enter key pressed')
    }
})
```

**Comment by KaneCohen** [comment]
Closed as duplicate.
