### ISSUE TITLE
Binding to dom el without constructor.

### ISSUE THREAD

**Issue by dmmulroy** [KaneCohen/tokenfield#7]
I'm trying to wrap this in a React component and would find a lot of use in being able to bind the functionality of the TokenField to an input element without having to call the constructor (i.e. being able to call a function instead of constructor).  As it is now, my component is rendering `<input ref="tokenfield" className="tokenfield-input" type="text" />`.  In `componentDidMount` i'm applying the TokenField as follows: 
```javascript
componentDidMount() {
  const { items, newItems, setItems } = this.props;
  new TokenField({
       el: ReactDOM.findDOMNode(this.refs.tokenfield),
       newItems,
       items,
       setItems
  });
}
```

I either have to assign the constructor to an unused variable or create an object that is immediately garbage collected.

**Comment by dmmulroy** [comment]
Realized that I needed a reference to the object anyways to handle adding and removing tokens so this is really a non-issue.

**Comment by KaneCohen** [comment]
Hey, thanks for the issue anyway. Made me think about what you want and in general possibility of integrating Tokenfield as a React Component.

Unfortunately there's no way for such library with such functionality to exist without some kind of instantiation. Tokenfield has to store internal state for various things (items, suggestions, cache) which means that this state has to be set up somewhere which is exactly where constructor comes into play.

Regarding React. I think at some point if there will be more requests I'll just port library to React.
